### ISSUE TITLE
You must call EnsureLoaded on the File plugin before using the DownloadCache

### ISSUE THREAD

**Issue by tbalcom** [MvvmCross/MvvmCross-Plugins#119] opened 2016-07-06 20:41 UTC
The update from 4.2.0 to 4.2.1 seems to sometimes cause issues if the project uses the DownloadCache and File plugins.  When this happens an exception is thrown during setup 

> You must call EnsureLoaded on the File plugin before using the DownloadCache

During the update NuGet shows an error claiming the various `Bootstrap` files can not be found.  The files are present and have not been modified from the originals.  It's not clear to me why NuGet can't see these files.

I've asked about this on [Stackoverflow](http://stackoverflow.com/questions/38212331/you-must-call-ensureloaded-on-the-file-plugin-before-using-the-downloadcache).

It seems like the DownloadCache plugin has a dependency on the File plugin but the DownloadCache is loaded before the File plugin has been loaded.  

One workaround is to manually remove the DownloadCache and File bootstrap loaders, then manually call EnsureLoaded on the plugins in the correct order:

```
    protected override void InitializeLastChance()
    {
        base.InitializeLastChance();
        MvvmCross.Plugins.File.PluginLoader.Instance.EnsureLoaded();
        MvvmCross.Plugins.DownloadCache.PluginLoader.Instance.EnsureLoaded();
    }
```
### Steps to reproduce
1. Update from 4.2.0 to 4.2.1 via NuGet.
2. Run the project.
3. An exception is thrown during setup.
### Expected behavior

The plugins should load automatically in the correct order.
### Actual behavior

An exception is thrown during setup.
### Configuration

**Version:** 4.2.1

**Platform:** Android

**Comment by Cheesebaron** [comment] 2016-07-07 08:26
Why are you not using bootstrap?

**Comment by Cheesebaron** [comment] 2016-07-07 08:27
Have you tried deleting the bootstrap files and adding them again?

**Comment by tbalcom** [comment] 2016-07-07 13:47
Deleting the bootstrap files and adding the packages back via NuGet didn't change anything. The Droid project has the following plugins:
1. Color
2. Json
3. Location
4. Messenger
5. ResourceLoader
6. Sqlite
7. WebBrowser

How does MvvmCross ensure the plugins are loaded in the correct order when one plugin depends on another plugin?

**Comment by Zolee007** [comment] 2016-07-14 13:36
I have run into the same problem, however I didn't delete the `Bootstrap` files, I have overriden the `DownloadCachePluginBootstrap`'s `Load`method to ensure the File plugin gets loaded before the DownloadCache plugin.

```
public class DownloadCachePluginBootstrap
        : MvxPluginBootstrapAction<MvvmCross.Plugins.DownloadCache.PluginLoader>
    {
        protected override void Load(IMvxPluginManager manager)
        {
            MvvmCross.Plugins.File.PluginLoader.Instance.EnsureLoaded();
            base.Load(manager);
        }
    }
```

**Comment by IlSocio** [comment] 2016-07-15 09:55
I faced the same issue too, thanks for the fix Zolee

**Comment by alfredp77** [comment] 2016-07-16 12:58
I'm on iOS, and MvvmCross 4.2.2. Putting in just Zolee's workaround doesn't work, I got the following exception:

> MvvmCross.Platform.Exceptions.MvxException: Could not find plugin loader for type MvvmCross.Plugins.File.PluginLoader

In addition to Zolee's workaround, I need to do the following:
- Force the File.PluginLoader to be registered by overriding AddPluginsLoaders in Setup:

```
protected override void AddPluginsLoaders(MvxLoaderPluginRegistry registry)
{
    registry.Register<MvvmCross.Plugins.File.PluginLoader, MvvmCross.Plugins.File.iOS.Plugin>();
    base.AddPluginsLoaders(registry);
}
```
- Subclass MvxLoaderPluginBootstrapAction and override PreLoad method to prevent the File.PluginLoader to be re-registered the second time:

```
    public class NoPreLoadPluginBootstrapAction<TPlugin, TPlatformPlugin> : MvxLoaderPluginBootstrapAction<TPlugin, TPlatformPlugin> where TPlugin : IMvxPluginLoader where TPlatformPlugin : IMvxPlugin
    {
        protected override void PreLoad(IMvxPluginManager manager)
        {
           // do nothing;
        }
    }
```
- Use that NoPreLoadPluginBootstrapAction instead of the MvxLoaderPluginBootstrapAction for FilePluginBootstrap:

```
    public class FilePluginBootstrap
        : NoPreLoadPluginBootstrapAction<MvvmCross.Plugins.File.PluginLoader, MvvmCross.Plugins.File.iOS.Plugin>
    {
    }
```

**Comment by alexsorokoletov** [comment] 2016-07-22 20:17
Just ran into the same issue, @Zolee007 's fix helped.

**Comment by Zolee007** [comment] 2016-07-28 13:03
Now that I also started to develop the iOS side of my application, I also run into the problem as @alfredp77 . I looked into the source code a bit to try to figure out the difference between the Android and iOS plugin loading.

I found that `MvxIosSetup`'s `CreatePluginManager` method creates a simple `MvxPluginManager`, while `MvxAndroidSetup`'s `CreatePluginManager` method creates an `MvxFilePluginManager` instance. Based on this fact I overridden the `CreatePluginManager` method of the `MvxIosSetup` class (in the actual `Setup` class) to use an `MvxFilePluginManager` instance as well:

```
protected override IMvxPluginManager CreatePluginManager()
{
    return new MvxFilePluginManager(".iOS", ".dll");
}
```

By doing this in addition of my previously posted workaround makes iOS working as well.

**Comment by flaviusdemian** [comment] 2016-07-31 21:23
@alfredp77 @Zolee007 I get this on iOS now... On a project it worked, on the current one I get this:

System.ArgumentException: Cannot create an instance of UpWorky.Mobile.iOS.Employee.NoPreLoadPluginBootstrapAction`2[TPlugin,TPlatformPlugin] because Type.ContainsGenericParameters is true.

Do you have some suggestions?

Thanks

**Comment by trevorchunestudy** [comment] 2016-08-02 21:56
I tried @Zolee007 's solution and had same problem that @alfredp77 had.  As opposed to the latter workaround, I just went back and used the old manual registration in Setup.cs which has changed slightly from previous versions.  I also removed the Bootstrap files for now until this get's sorted out. 

This works fine for 4.2.2.

```
        protected override void AddPluginsLoaders(MvxLoaderPluginRegistry registry)
        {
            registry.Register<MvvmCross.Plugins.DownloadCache.PluginLoader, MvvmCross.Plugins.DownloadCache.iOS.Plugin>();
            registry.Register<MvvmCross.Plugins.File.PluginLoader, MvvmCross.Plugins.File.iOS.Plugin>();
            base.AddPluginsLoaders(registry);
        }

        protected override void InitializeLastChance()
        {

            base.InitializeLastChance();
            MvvmCross.Plugins.File.PluginLoader.Instance.EnsureLoaded();
            MvvmCross.Plugins.Json.PluginLoader.Instance.EnsureLoaded();
            PluginLoader.Instance.EnsureLoaded();
        }
```

**Comment by flaviusdemian** [comment] 2016-08-03 00:49
I will check in a few hours. Thanks

**Comment by lisannefoget** [comment] 2016-08-04 13:51
I ran into the same issue as @alfredp77, and @Zolee007's first workaround fixed it for me on Android. Once I started on iOS, @Zolee007 's workaround to add this into the Setup.cs worked great!

`protected override IMvxPluginManager CreatePluginManager()`
`{`
        `return new MvxFilePluginManager(".iOS", ".dll");`
`}`

I didn't have to remove any of the original Bootstrap files or manually register the plugin loaders.

**Comment by Cheesebaron** [comment] 2016-08-15 08:02
@SeeD-Seifer any idea what is going on? I haven't debugged this yet, but seems like the MvxPluginManager does not pick up some plugins.

**Comment by Cheesebaron** [comment] 2016-08-19 09:44
OK. So I've been debugging a bit. The problem seems to be that the `Load` method is called in the order the bootstrap files are discovered?

So if I remove the boostrap files for File and DownloadCache and make a new where both are defined in this order:

```
public class FilePluginBootstrap
    : MvxPluginBootstrapAction<MvvmCross.Plugins.File.PluginLoader>
{
}

public class DownloadCachePluginBootstrap
    : MvxPluginBootstrapAction<MvvmCross.Plugins.DownloadCache.PluginLoader>
{
}
```

It seems to work fine.

If I swap the order in the file to: 

```
public class DownloadCachePluginBootstrap
    : MvxPluginBootstrapAction<MvvmCross.Plugins.DownloadCache.PluginLoader>
{
}

public class FilePluginBootstrap
    : MvxPluginBootstrapAction<MvvmCross.Plugins.File.PluginLoader>
{
}
```

💥  everything blows up...

How this worked before I have no idea, maybe by coincidence? I've reviewed the changes @SeeD-Seifer made to the plugins registry in https://github.com/MvvmCross/MvvmCross/commit/ffd2b3390a5121b4030aa38fad2d85cd4fe8b8a4 and I don't see how it would change anything.

Now! On the other side this https://github.com/MvvmCross/MvvmCross-Plugins/commit/4e8ea9fcf163ceb57a7dd99f0a930ef600b8a541 has added more stuff to the plugin loader, which matches the crash I get

**Comment by alexshikov** [comment] 2016-08-19 10:08
@Cheesebaron I'll review the thread and the code later today and let you know when find the reason of the issue. Highly suspect this is somehow related to my changes.

**Comment by Cheesebaron** [comment] 2016-08-19 10:23
@SeeD-Seifer I am not sure it is actually your changes that did it. However, rather @promontis' changes which explicitly ask for the File plugin.

I think we need to do something about discovering dependencies in Plugins and fix load order.

**Comment by alexshikov** [comment] 2016-08-21 00:13
@Cheesebaron you was right, @promontis commit broke the plugin loading.

Apart from direct fix I have noticed few things:
1. DownloadCache plugin depends on File plugin implementation, but there is no NuGet dependency. I understand why it's exist in current way, but wouldn't it be easier to make DownloadCache dependent on File? I hardly believe there is anybody using custom implementation of IMvxStore instead of File plugin.
2. Bootstrap files actually loaded in random order. There is a project in MvvmCross-Samples repo **WorkingWithCollection** that uses both plugins but loads them in _correct_ order so the issue did not reproduced there. Does it make sense to force bootstrap loader to sort found types by name and then load them? I'm not sure how often it is important, but it's annoying when there is a case with random behaviour...

**Comment by promontis** [comment] 2016-08-21 11:30
Ah yes,  the commit I did eager loads the File plugin, which it shouldn't do. The fix from @SeeD-Seifer fixes that, awesome!

I agree that the dependencies between plugins, the loading of them, and the order in which they load should be fixed. Already bumped my head several times because of it. I did talk to @martijn00 at the last mvvmcross meetup we had about this... maybe he can jump into this conversation? I thought the solution he proposed was to actually remove the bootstrap loaders and initialize the plugins yourself in the correct order.

**Comment by martijn00** [comment] 2016-08-21 23:58
@promontis Yes, to manually register the plugins could be a temporary solution. I would like to look into how we can make a proper fix in combination with moving the plugins to Net Standard (PCL) based setup. @Cheesebaron already looked into this a bit in https://github.com/MvvmCross/MvvmCross-Plugins/pull/63#issuecomment-191451635

**Comment by alexshikov** [comment] 2016-08-22 08:59
To ensure plugins loaded in the same order **MvxBootstrapRunner** should be updated.
This is the method from [MvxBootstrapRunner.cs](https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Platform/Platform/Platform/MvxBootstrapRunner.cs):

``` csharp
        public virtual void Run(Assembly assembly)
        {
// types order is not determined.
            var types = assembly.CreatableTypes()
                                .Inherits<IMvxBootstrapAction>();

            foreach (var type in types)
            {
                this.Run(type);
            }
        }
```

Simple solution is to always sort types by Name or FullName.

**Comment by Cheesebaron** [comment] 2016-08-22 09:00
That would solve it? F comes after D?

**Comment by promontis** [comment] 2016-08-22 09:05
Haha... that's what I first did as well :) sorting the plugins by name. Now I just manually register the plugins, so that I minimize the performance hit of using reflection.

**Comment by alexshikov** [comment] 2016-08-22 09:08
@Cheesebaron when I launched **MvvmCross-Samples/WorkingWithCollection** project which uses File and DownloadCache plugins I was surprised, it didn't crash with MvvmCross 4.2.3 NuGet packages. It appeared, for some reason MvxBootstrapRunner loaded File plugin first, just because `assembly.CreatableTypes()` returned this type first.

Hacking MvxBootstrapRunner to sort types lead to stable reproduce of the issue. Can't explain why.

**Closed as completed** 2016-08-23 06:59 UTC

**Comment by flaviusdemian** [comment] 2016-09-24 15:51
Hy Guys, this is a bit confusing...can somebody put a gist with the whole correct steps? I am using the Support JASlider also. Maybe this adds some problems as well.

`  
                               Window = new UIWindow(UIScreen.MainScreen.Bounds);

```
            var setup = new Setup(this, Window);
            setup.Initialize();

            var startup = Mvx.Resolve<IMvxAppStart>();
            startup.Start();

            Window.MakeKeyAndVisible();`
```

In the Setup class I have

`protected override IMvxIosViewPresenter CreatePresenter()
        {
            return new MvxSidePanelsPresenter((MvxApplicationDelegate)ApplicationDelegate, Window);
        }`

Should the download cache plugin bootStrapper look like this?

`public class DownloadCachePluginBootstrap
        : MvxLoaderPluginBootstrapAction<MvvmCross.Plugins.DownloadCache.PluginLoader, MvvmCross.Plugins.DownloadCache.iOS.Plugin>
    {
    }`

I have upgraded the Collections sample to 4.2.3 and it works but in our project it does not work... This is very strange.

**Comment by Cheesebaron** [comment] 2016-09-27 19:10
This is fixed in 4.3.0

**Comment by flaviusdemian** [comment] 2016-09-27 19:39
Thank you very much.

**Comment by luigisaggese** [comment] 2017-04-26 09:29
@Cheesebaron I have same issue on 4.4.0 (In release mode -> Linking All assemblies)
This workaround still work to solve (inside Setup.cs)

```
protected override IMvxPluginManager CreatePluginManager()
{
	return new MvxFilePluginManager(".iOS", ".dll");
}
```

**Comment by Cheesebaron** [comment] 2017-04-26 13:45
So `MvxFilePluginManager` gets linked away?

This issue is about order of plugins being loaded. Not linking issues.

**Comment by luigisaggese** [comment] 2017-04-26 13:57
Yes MvxFilePluginManager is linked away and with this method overriding i have solved it
