### ISSUE TITLE
DownloadCache Plugin fails to display image on beta7 android

### ISSUE THREAD

**Issue by deanmarcussen** [MvvmCross/MvvmCross-Plugins#41] opened 2016-01-07 10:04 UTC
I'm experiencing a similar issue to that discussed in the closed issue "DownloadCache Plugin (beta4) not always loading image in Android #19"

The code I'm using includes the fix in ImageHelperOnImageChanged https://github.com/MvvmCross/MvvmCross/commit/d7733f2fc65b36502f59052bce1bf824948f38b9

which call SetImageBitmap on the UI thread 

The exception I get is as below

[image] Exception :System.ArgumentException: 'jobject' must not be IntPtr.Zero.
[image] Parameter name: jobject
[image]   at Android.Runtime.JNIEnv.CallObjectMethod (IntPtr jobject, IntPtr jmethod) [0x00010] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:170 
[image]   at Java.Lang.Object.ToString () [0x00043] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Java.Lang.Object.cs:250 
[image]   at AroundMe2.Droid.Services.MvxImageViewCustom+<ImageHelperOnImageChanged>c__AnonStorey0.<>m__0 () [0x00017] in /Users/deanmarcussen/Projects/AroundMe2/Wales/Droid/Lib/AroundMe2.Droid/Services/MvxImageViewCustom.cs:140 
[image] Exception :System.ArgumentException: 'jobject' must not be IntPtr.Zero.
[image] Parameter name: jobject
[image]   at Android.Runtime.JNIEnv.CallObjectMethod (IntPtr jobject, IntPtr jmethod) [0x00010] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:170 
[image]   at Java.Lang.Object.ToString () [0x00043] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Java.Lang.Object.cs:250 
[image]   at AroundMe2.Droid.Services.MvxImageViewCustom+<ImageHelperOnImageChanged>c__AnonStorey0.<>m__0 () [0x00017] in /Users/deanmarcussen/Projects/AroundMe2/Wales/Droid/Lib/AroundMe2.Droid/Services/MvxImageViewCustom.cs:140 

What I've discovered is that my images are around 235000 bytes and the default image configuration.MaxInMemoryBytes of 4000000 only allows one, possibly two images into the DictionaryCache _entriesByHttpUrl in MvxImageCache.

As the images are disposed of in ReduceSizeIfNecessary DisposeIfDisposable is called on the image in the dictionary cache.

When the ImageChanged event is called in FireImageChanged in MvxImageHelper it is recieved by ImageHelperOnImageChanged. If I try and access the image bitmap held in mvxValueEventArgs prior to the using (var h = new Handler(Looper.MainLooper)) block in ImageHelperInImageChanged I have access to the bitmap. However as soon as I try to access the bitmap inside the using block (back on the UI thread) it may have been disposed and may generate the above exception.

As a short term solution I can increase the size of the maxInMemoryBytes, which works well, but I cannot assume that the images won't change in size over time, and begin to exceed the cache again.

Alternatively I've added a line to create a new copy of the image that gets sent via mvxValueEventArgs prior to the using block, loading that image , then disposing of it. If I do this things seem to work well, but I'm having to copy a bitmap and then dispose of it, which seems like unnecessary work. 

Here is the changes I've made , any suggestions, or more appropriate work arounds would be appreciated.

```
    private void ImageHelperOnImageChanged(object sender, MvxValueEventArgs<Bitmap> mvxValueEventArgs)
    {
        var tempImage = mvxValueEventArgs.Value.Copy (mvxValueEventArgs.Value.GetConfig (), mvxValueEventArgs.Value.IsMutable);

        using (var h = new Handler(Looper.MainLooper))
            h.Post(() =>
                {
                    try {
                        SetImageBitmap(tempImage);
                        tempImage.DisposeIfDisposable();
                    } catch (Exception e)
                    {
                        Log.Debug("image", "Exception :" + e.ToString());
                    }
                });
    }
```

**Comment by alexshikov** [comment] 2016-03-22 14:13
The stack trace above happens because the MvxImageView disposed between `ImageHelperOnImageChanged` and `SetImageBitmap()` methods call. This issue is fixed by this commit https://github.com/MvvmCross/MvvmCross/commit/382647d14b8eff07cd2ac579afa8da83718ad12f

Though, there is actually another case which also described above (when the Bitmap disposed when `SetImageBitmap()` called for existing MvxImageView). Here is how it happens:
- `SetImageBitmap()`  method called while both MvxImageView and the Bitmap still alive (NOTE: this is UI-thread)
- MvxImageCache processing `ReduceSizeIfNecessary()` on the **non** UI-thread and calling for `DisposeIfDisposable()` for the Bitmap from the previous step

As a result the application is crashed with the next stack trace:

```
 Stacktrace:

   at <unknown> <0xffffffff>
   at (wrapper managed-to-native) object.wrapper_native_0x7fb214a1a0 (intptr,intptr,intptr,intptr,Android.Runtime.JValue*) <IL 0x0002c, 0xffffffff>
   at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (intptr,intptr,intptr,Android.Runtime.JValue*) <IL 0x00073, 0x00247>
   at Android.Widget.ImageView.SetImageBitmap (Android.Graphics.Bitmap) <IL 0x00092, 0x0035f>
   at MvvmCross.Binding.Droid.Views.MvxImageView/<>c__DisplayClass18_0.<ImageHelperOnImageChanged>b__0 () <IL 0x00011, 0x00093>
   at Java.Lang.Thread/RunnableImplementor.Run () <IL 0x00011, 0x00093>
   at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) <IL 0x0000a, 0x000b7>
   at (wrapper dynamic-method) object.f50edba1-9cb5-4d59-9da0-06e77c619fd4 (intptr,intptr) <IL 0x00011, 0x0001f>
   at (wrapper native-to-managed) object.f50edba1-9cb5-4d59-9da0-06e77c619fd4 (intptr,intptr) <IL 0x00026, 0xffffffff>
```

**Solution**
It is possible to check is Bitmap exist or not just before it's rendered. But because it is disposed on another thread, there is always be a race. And it is impossible to **lock** bitmap existence check.

But it is possible to dispose Bitmap on UI-thread, which ensures existence check and render processed on the same thread (and so that synchronised)

Commit is coming...

**Comment by alexshikov** [comment] 2016-03-22 15:30
Simple project with reproduce and solution described/implemented https://github.com/SeeD-Seifer/MvxBitmap

**Closed as completed** 2016-05-13 12:08 UTC
Labels: bug
